window.kakao=window.kakao||{},window.kakao.maps=window.kakao.maps||{},window.daum&&window.daum.maps?window.kakao.maps=window.daum.maps:(window.daum=window.daum||{},window.daum.maps=window.kakao.maps),function(){function t(){if(u.length){n(p[u.shift()],t).start()}else a()}function n(t,n){var a=document.createElement("script");return a.onload=n,a.onreadystatechange=function(){/loaded|complete/.test(this.readyState)&&n()},{start:function(){a.src=t||"",
document.getElementsByTagName("head")[0].appendChild(a),a=null}}}function a(){for(;o[0];)o.shift()();e.readyState=2}var e=kakao.maps=kakao.maps||{};if(void 0===e.readyState)e.onloadcallbacks=[],e.readyState=0;else if(2===e.readyState)return;e.URI_FUNC={ROADMAP:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD02/v10_3fw8s/latest/"+a+"/"+n+"/"+t+".png"},HYBRID:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD_SKYH02/v09_m79gz/latest/"+a+"/"+n+"/"+t+".png"},ROADVIEW:function(t,n,a){
return"mts.daumcdn.net/api/v1/tile/PNGSD_RV02/v07_d8e9f/latest/"+a+"/"+n+"/"+t+".png"},BICYCLE:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD_BIKE02/v04_tjnvy/latest/"+a+"/"+n+"/"+t+".png"},USE_DISTRICT:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD_CAD02/v07_fqsee/latest/"+a+"/"+n+"/"+t+".png"},SR:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD_SR02/v10_re5nm/latest/"+a+"/"+n+"/"+t+".png"},BBOUND:function(t,n,a){
return"mts.daumcdn.net/api/v1/tile/PNGSD_BBOUND02/v07_wlvto/latest/"+a+"/"+n+"/"+t+".png"},HBOUND:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNGSD_HBOUND02/v07_xs9ij/latest/"+a+"/"+n+"/"+t+".png"},TRAFFIC:function(t,n,a){return"r.maps.daum-img.net/mapserver/file/realtimeroad/L"+a+"/"+n+"/"+t+".png"},ROADMAP_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG02/v10_453ky/latest/"+a+"/"+n+"/"+t+".png"},HYBRID_HD:function(t,n,a){
return"mts.daumcdn.net/api/v1/tile/PNG_SKYH02/v09_1ygpp/latest/"+a+"/"+n+"/"+t+".png"},ROADVIEW_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG_RV02/v07_zxrda/latest/"+a+"/"+n+"/"+t+".png"},BICYCLE_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG_BIKE02/v04_q8umj/latest/"+a+"/"+n+"/"+t+".png"},USE_DISTRICT_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG_CAD02/v07_6erp3/latest/"+a+"/"+n+"/"+t+".png"},SR_HD:function(t,n,a){
return"mts.daumcdn.net/api/v1/tile/PNGSD_SR02/v10_re5nm/latest/"+a+"/"+n+"/"+t+".png"},BBOUND_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG_BBOUND02/v07_9mynq/latest/"+a+"/"+n+"/"+t+".png"},HBOUND_HD:function(t,n,a){return"mts.daumcdn.net/api/v1/tile/PNG_HBOUND02/v07_spiio/latest/"+a+"/"+n+"/"+t+".png"},TRAFFIC_HD:function(t,n,a){return"r.maps.daum-img.net/mapserver/file/realtimeroad_hd/L"+a+"/"+n+"/"+t+".png"}},e.VERSION={ROADMAP_SUFFIX:"",SKYVIEW_VERSION:"160114",
SKYVIEW_HD_VERSION:"160107"},e.RESOURCE_PATH={ROADVIEW_AJAX:"//t1.daumcdn.net/roadviewjscore/core/css3d/200204/standard/1580795088957/roadview.js",ROADVIEW_CSS:"//t1.daumcdn.net/roadviewjscore/core/openapi/standard/240925/roadview.js"}
;for(var i,s="https:"==location.protocol?"https:":"http:",r="",d=document.getElementsByTagName("script"),c=d.length;i=d[--c];)if(/\/(beta-)?dapi\.kakao\.com\/v2\/maps\/sdk\.js\b/.test(i.src)||/\/map_js_init\/open4\.test\.js\b/.test(i.src)||/\/map_js_init\/open4\.cbt\.js\b/.test(i.src)){r=i.src;break}d=null;var o=e.onloadcallbacks,u=["v3"],m="",p={v3:s+"//t1.daumcdn.net/mapjsapi/js/main/4.4.19/kakao.js",services:s+"//t1.daumcdn.net/mapjsapi/js/libs/services/1.0.2/services.js",
drawing:s+"//t1.daumcdn.net/mapjsapi/js/libs/drawing/1.2.6/drawing.js",clusterer:s+"//t1.daumcdn.net/mapjsapi/js/libs/clusterer/1.0.9/clusterer.js"},l=function(t){var n={};return t.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(t,a,e){n[a]=e}),n}(r);m=l.appkey,m&&(e.apikey=m),e.version="4.4.19";var v=l.libraries;if(v&&(u=u.concat(v.split(","))),"false"!==l.autoload){for(var c=0,_=u.length;c<_;c++)!function(t){t&&document.write('<script charset="UTF-8" src="'+t+'"><\/script>')}(p[u[c]])
;e.readyState=2}e.load=function(n){switch(o.push(n),e.readyState){case 0:e.readyState=1,t();break;case 2:a()}}}();